"""Which published prose is entirely machine-written, and how we know.

A reader is entitled to know when nothing on a page passed through a
person. The honest way to answer that is to record it when it happens,
not to guess afterwards from how the writing sounds: a detector would be
wrong about the Commissioner's own prose eventually, and being wrong in
that direction is worse than saying nothing.

So provenance is a fact we store. When generated text is accepted into a
section we keep the generator, an input class, and a hash of exactly what
was accepted. A section is fully AI-generated for as long as its current
text still hashes to that value. One edited character changes the hash and
the claim stops being true, which is the correct outcome and needs no
further bookkeeping.

Nothing here can leak. `method` is a key into a fixed table of input-class
descriptions rather than free text, so a filesystem path, a private brief
or a prompt cannot be stored in it even by mistake, and an unrecognised key
degrades to "not recorded" instead of being echoed.
"""
from __future__ import annotations

import hashlib

from leaguepage.storage import Storage

# The providers we are willing to name. A generator we cannot identify is
# reported as unknown; it never guesses, because a wrong badge is a false
# statement about who wrote something.
GENERATORS = {
    "claude-code": "Claude Code",
    "chatgpt": "ChatGPT",
}

# What the generator was working from, described as a class of input. These
# are the only strings that can ever reach a reader, which is what makes the
# privacy guarantee structural rather than a review step.
METHODS = {
    "matchup-brief": ("from synced Sleeper league data and the structured "
                      "matchup brief"),
    "section-brief": ("from synced Sleeper league data and the section's "
                      "editorial brief"),
    "transactions": ("from synced Sleeper league data and deterministic "
                     "transaction analysis"),
    "draft-data": "from the league's synced draft results and reference ranks",
}

UNKNOWN_GENERATOR = "an AI assistant (provider not recorded)"
UNKNOWN_METHOD = "Generation method not recorded."
NO_EDITS = "No Commissioner edits."


def text_sha(text: str | None) -> str:
    """Content hash. Line endings are normalised because an editor changing
    CRLF to LF is not the Commissioner rewriting a sentence."""
    normalised = (text or "").replace("\r\n", "\n").strip()
    return hashlib.sha256(normalised.encode("utf-8")).hexdigest()


def record(storage: Storage, *, league_slug: str, season: str, issue_key: str,
           section: str, generator: str | None, method: str | None,
           text: str) -> None:
    """Remember that this exact text was generated, and by what."""
    storage.set_prose_provenance(
        league_slug=league_slug, season=season, issue_key=issue_key,
        section=section,
        generator=generator if generator in GENERATORS else None,
        method=method if method in METHODS else None,
        generated_sha=text_sha(text))


def forget(storage: Storage, *, league_slug: str, season: str, issue_key: str,
           section: str) -> None:
    storage.clear_prose_provenance(league_slug=league_slug, season=season,
                                   issue_key=issue_key, section=section)


def state_for(storage: Storage, *, league_slug: str, season: str,
              issue_key: str, section: str, text: str | None) -> dict | None:
    """Provenance for this section's CURRENT text, or None.

    None covers both "we never recorded anything" and "we did, and he has
    since edited it" -- from a reader's point of view those are the same
    answer, which is that this is not machine-written prose standing on its
    own.
    """
    row = storage.get_prose_provenance(league_slug, season, issue_key, section)
    if not row or not row.get("generated_sha"):
        return None
    if text_sha(text) != row["generated_sha"]:
        return None
    return describe(row.get("generator"), row.get("method"))


def describe(generator: str | None, method: str | None) -> dict:
    """The public caption, its parts, and what a screen reader should say."""
    label = GENERATORS.get(generator or "", UNKNOWN_GENERATOR)
    detail = METHODS.get(method or "")
    caption = f"AI-generated by {label}"
    if detail:
        caption += f" {detail}"
    caption += f". {NO_EDITS}" if detail else f". {UNKNOWN_METHOD} {NO_EDITS}"
    return {
        "generator": generator if generator in GENERATORS else None,
        "generator_label": label,
        "method": method if method in METHODS else None,
        "caption": caption,
        # The badge is a neutral mark plus the provider's name in text. It is
        # deliberately not a reproduction of anyone's logo.
        "badge_text": "AI",
    }


def for_sections(storage: Storage, league_slug: str, season: str,
                 issue_key: str, sections: list[dict]) -> dict[str, dict]:
    """{section_key: provenance} for the ones that are fully generated."""
    out = {}
    for s in sections:
        key = s.get("module_key") or s.get("section")
        if not key:
            continue
        st = state_for(storage, league_slug=league_slug, season=season,
                       issue_key=issue_key, section=key,
                       text=s.get("content_md"))
        if st:
            out[key] = st
    return out


# Force Flow's reading of the week is produced by deterministic analysis
# rather than by a language model. Badging it "by Claude Code" would be a
# false statement about who wrote it, so it gets its own caption that
# claims only what is true: a machine wrote it, and here is what from.
def describe_machine(method: str | None) -> dict:
    detail = METHODS.get(method or "")
    caption = "Generated automatically"
    caption += f" {detail}." if detail else f". {UNKNOWN_METHOD}"
    return {
        "generator": None,
        "generator_label": "deterministic analysis",
        "method": method if method in METHODS else None,
        "caption": f"{caption} {NO_EDITS}",
        "badge_text": "AUTO",
    }
